name: "Require Semantic Versioning Bump"
description: "Requires that the PR being merged has bumped the version to a valid semver"
inputs:
  github-token:
    description: A GitHub token.
    required: false
    default: ${{ github.token }}
  file:
    description: "The relative path (from your project root) to the file with your version identifier in it. Do not include the initial backslash."
    required: true
  pattern:
    description: "The regex pattern that should be used to parse the version from your version file. Note: because the string will be converted to a regex the backslashes need to be double escaped."
    required: true
runs:
  using: "node16"
  main: "index.js"
branding:
  icon: tag
  color: red